language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace --use-cython
  - python setup.py sdist bdist_wheel
  - pip install dist/*.whl
  - python build_tests.py
script:
  - py.test
