# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- "*"

variables:
  project_name: 'cython-pocketfft'

jobs:
- job: generator
  steps:
  - checkout: none
  - task: PythonScript@0
    name: strat
    inputs:
      scriptSource: 'inline'
      script: |
        import json
        PLATFORMS = {
            'linux':'ubuntu-latest',
            # 'mac':'macOS-latest',
            'windows':'windows-latest',
        }
        PY_VERSIONS = ['3.5', '3.6', '3.7']
        d = {}
        for pl_key, pl_img in PLATFORMS.items():
            for py_v in PY_VERSIONS:
                job_key = '{}-Python{}'.format(pl_key, ''.join(py_v.split('.')))
                d[job_key] = {
                    'imageName':pl_img,
                    'python.version':py_v,
                    'artifact_name':'dist-{}-{}'.format(pl_key, py_v)
                }
        s = json.dumps(d)
        print('##vso[task.setVariable variable=mtrx;isOutput=true]{}'.format(s))

- job: compile
  dependsOn: generator
  pool:
    vmImage: $(imageName)
  strategy:
    matrix: $[ dependencies.generator.outputs['strat.mtrx'] ]
  steps:
  - bash: echo $(build_types)
  - template: 'ci/templates/build-steps.yml'
    parameters:
      use_cython: 'true'
      test_mode: 'develop'

- job: testFromWheel
  dependsOn:
  - generator
  - compile
  pool:
    vmImage: $(imageName)
  strategy:
    matrix: $[ dependencies.generator.outputs['strat.mtrx'] ]
  steps:
  - template: 'ci/templates/build-steps.yml'
    parameters:
      test_mode: 'wheel'

- job: testFromSDist
  dependsOn:
  - generator
  - compile
  pool:
    vmImage: $(imageName)
  strategy:
    matrix: $[ dependencies.generator.outputs['strat.mtrx'] ]
  steps:
  - template: 'ci/templates/build-steps.yml'
    parameters:
      test_mode: 'sdist'
