parameters:
  platforms: {}         # map of {'osName':'vmImage'}
  pythonVersions: {}    # map of {'someKey':{'dotted':'X.Y','number':'XY'}} where 'X' is major and 'Y' is minor
                        # 'someKey' can be anything. it only exists to make yaml formatting easier
  jobs: []

jobs:
- ${{ each job in parameters.jobs }}:
  - ${{ each pair in job }}:
    ${{ if ne(pair.key, 'strategy') }}:
      ${{ pair.key }}: ${{ pair.value }}
  strategy:
    matrix:
    ${{ each platform in parameters.platforms }}:
      ${{ each pyVersion in parameters.pythonVersions }}:
        ${{ platform.key }}-Python${{ pyVersion.value.dotted }}:
          osName: ${{ platform.key }}
          imageName: ${{ platform.value }}
          python.version: ${{ pyVersion.value.dotted }}
          artifact_name: ${{ pyVersion.value.number }}
